### DISCUSSION TITLE
스크롤바 꾸미기

### DISCUSSION THREAD

**Discussion by miniposi** [miniposi/Oasis#7] [Study]
```css
/* 스크롤바 디자인 */
::-webkit-scrollbar {
  width: 12px; /* 스크롤바의 너비 */
}

/* 스크롤바 트랙 */
::-webkit-scrollbar-track {
  background: #f1f1f1; /* 스크롤바 트랙의 배경색 */
}

/* 스크롤바 색상 */
::-webkit-scrollbar-thumb {
  background: #888; /* 스크롤바 색상 */
  border-radius: 6px; /* 스크롤바의 모서리 반경 */
}

/* 스크롤바 마우스 오버 시 색상 */
::-webkit-scrollbar-thumb:hover {
  background: #555; /* 스크롤바 색상 변경 */
}
```

❗`width`를 지정해주지 않으면 나머지 코드도 적용되지 않는다
